### ISSUE TITLE
Failed to setup when Fixed price

### ISSUE THREAD

**Issue by ermitovski** [MTrab/energidataservice#791]
### Describe the issue

Hi,
I noticed this after upgrading to 2025.9.0 but I don't know for sure it's related.
Fixed price configs are on "Failed to setup" and the logs report the following. I had a config working for some time and when I try to configure a new without adding any special templating it also fails.

I've tried with specific country setup and it works as expected.

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/energidataservice/api.py:189
integration: Energi Data Service (documentation, issues)
First occurred: 3 September 2025 at 22:03:53 (155 occurrences)
Last logged: 16:54:10

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/energidataservice/config_flow.py", line 110, in _do_update
    await async_setup_entry(self.hass, self.config_entry)
  File "/config/custom_components/energidataservice/__init__.py", line 54, in async_setup_entry
    result = await _setup(hass, entry)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/energidataservice/__init__.py", line 189, in _setup
    await get_new_data(0)
  File "/config/custom_components/energidataservice/__init__.py", line 155, in get_new_data
    await api.update()
  File "/config/custom_components/energidataservice/api.py", line 189, in update
    if len(api.result) == 0:
           ^^^^^^^^^^
AttributeError: 'Connector' object has no attribute 'result'
```

### What version of Home Assistant Core has the issue?

core-2025.9.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

[home-assistant_energidataservice_2025-09-04T15-01-08.138Z.log](https://github.com/user-attachments/files/22141554/home-assistant_energidataservice_2025-09-04T15-01-08.138Z.log)

### Anything in the logs that might be useful for us?

```txt

```

**Comment by ermitovski** [comment]
Thanks!! Upgraded and it works
